site:
  title: Cours de formation du GBIF
  start_page: ROOT::index.adoc
  keys:
    language: fr
content:
  sources:
    - url: .
      start_path: ./fr/home
      branches: HEAD
    - url: .
      start_path: ./fr/intro-to-gbif
      branches: HEAD
    - url: .
      start_path: ./fr/data-mobilization
      branches: HEAD
    - url: .
      start_path: ./fr/data-use
      branches: HEAD
    - url: .
      start_path: ./fr/dna-barcoding
      branches: HEAD
    - url: .
      start_path: ./fr/nodes
      branches: HEAD
    - url: .
      start_path: ./fr/epn
      branches: HEAD
    - url: .
      start_path: ./fr/grscicoll
      branches: HEAD
    - url: .
      start_path: ./fr/project-planning
      branches: HEAD
output:
  clean: false
  dir: ./output/fr
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  extensions:
  - ./lib/asciidoctor-question
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Contenu de la page'
    language: fr
    null: ‚êÄ
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [fr]
